/**
 * Мемные скины (картинки в assets/images/skins/).
 * caseGroup: premium — выпадают в Premium Case и в гараже.
 * @type {{ id: string, name: string, rarity: string, file: string }[]}
 */
export const MEME_SKIN_DEFS = [
  { id: "cust_mayl", name: "Мяул", rarity: "Mythic", file: "mayl.png" },
  { id: "cust_y", name: "ЪУЪ", rarity: "Legendary", file: "y.png" },
  { id: "cust_beluga", name: "БЕЛУГА", rarity: "Legendary", file: "beluga.png" },
  { id: "cust_stoyak", name: "СТОЯК РОНАЛДУ", rarity: "Epic", file: "stoyak.png" },
  { id: "cust_tolik", name: "ТОЛИК ЭТО ПОДЪЕЗД", rarity: "Top", file: "tolik.png" },
  { id: "cust_stant", name: "СТАНТИКА 12 О КЛОК", rarity: "Mythic", file: "stant.png" },
  { id: "cust_okak", name: "ОКАК", rarity: "Top", file: "okak.png" },
  { id: "cust_misha", name: "МИША ТЫ ЧТО ПУКНУЛ???", rarity: "Top", file: "misha.png" },
  { id: "cust_ptyt", name: "РТУТЬ", rarity: "Legendary", file: "ptyt.png" },
  { id: "cust_medved", name: "ЯДЕРНЫЙ СНЕГ", rarity: "Legendary", file: "medved.png" },
  { id: "cust_e", name: "ТОРНАДО", rarity: "Mythic", file: "e.png" },
  { id: "cust_kazahstan", name: "КАЗАХСТАН УГРОЖАЕТ НАМ БОМБАРДИРОВКОЙ", rarity: "Mythic", file: "kazahstan.png" },
  { id: "cust_seks", name: "СЕКС СЕКС ПОРНО СИСЬКИ ПИСЬКИ", rarity: "Legendary", file: "seks.png" },
  { id: "cust_ben", name: "БЕН", rarity: "Top", file: "ben.png" },
  { id: "cust_mik", name: "МЕДНЫЙ БЫК", rarity: "Epic", file: "bik.png" },
  { id: "cust_ser", name: "СЭР ДА СЭР", rarity: "Mythic", file: "ser.png" },
  { id: "cust_dmkfjggkd", name: "БЛЯ ЧЁ Я НЕСУ", rarity: "Top", file: "dmkfjggkd.png" },
  { id: "cust_kola", name: "КОЛА ПЕПСИ АНДРЕЙ СЕКСИ", rarity: "Epic", file: "kola.png" },
  { id: "cust_mefedronchik", name: "МЕФЕДРОНЧИК", rarity: "Mythic", file: "mefedronchik.png" },
  { id: "cust_red", name: "Я УЖЕ КРАСНЫЙ", rarity: "Legendary", file: "red.png" },
  { id: "cust_elprimo", name: "ЕЛЬ ЖИРПРИМО", rarity: "Top", file: "elprimo.png" },
  { id: "cust_gavko", name: "ГАВКОШМЫГ", rarity: "Mythic", file: "gavko.png" },
  { id: "cust_wtf", name: "ШО У ВАС ЗДЕСЬ ПРОИСХОДИТ?!", rarity: "Legendary", file: "wtf&.png" },
  { id: "cust_iba", name: "IБА ЧОТКО", rarity: "Legendary", file: "iba.png" },
  { id: "cust_sova", name: "А Я ДУМЛАА СОВА", rarity: "Legendary", file: "sova.png" },
  { id: "cust_sixnine", name: "SIX NINE", rarity: "Top", file: "sixnine.png" },
  { id: "cust_dodep", name: "ДОДЕП", rarity: "Mythic", file: "dodep.png" },
  { id: "cust_dati", name: "ДА ТЫ ШУЕШЬ", rarity: "Legendary", file: "dati.png" },
  { id: "cust_mir", name: "МИР ЖЕЛТОК...", rarity: "Mythic", file: "mir.png" },
  { id: "cust_vinograd", name: "Я ВО ВСЁМ ВИНОГРАД...", rarity: "Mythic", file: "vinograd.png" },
  { id: "cust_zemla", name: "ЗЕМЛЯ ТЕБЕ ПУЗОМ...", rarity: "Mythic", file: "zemla.png" },
  { id: "cust_kartel", name: "КАРТЕЛЬ", rarity: "Epic", file: "kartel.png" },
  { id: "cust_tzk", name: "ТЦК", rarity: "Epic", file: "tzk.png" },
  { id: "cust_patron", name: "ПЁС ПАТРОН", rarity: "Mythic", file: "patron.png" },
  { id: "cust_fifetwo", name: "52", rarity: "Legendary", file: "fifetwo.png" },
  { id: "cust_kyki", name: "КУКИ", rarity: "Legendary", file: "kyki.png" },
  { id: "cust_misha2", name: "МИША ИДИ В САДИК", rarity: "Top", file: "misha2.png" },
  { id: "cust_ona", name: "ОНА СКЗААЛА ЗАЕБИСЬ", rarity: "Top", file: "ona.png" },
  { id: "cust_eldzeefka", name: "ЭЛДЖЕЕВКА", rarity: "Legendary", file: "eldzeefka.png" },
  { id: "cust_exal", name: "ЕХАЛ Я ДОМОЙ С РАБОТЫ", rarity: "Legendary", file: "exal.png" },
  { id: "cust_echkere", name: "ЕЩКЕРЕ", rarity: "Legendary", file: "echkere.png" },
  { id: "cust_pepe", name: "ЛЯГУШЁНОК ПЕПЕ", rarity: "Top", file: "pepe.png" },
  { id: "cust_kogda", name: "КОГДА НЕ БРИЛ МОШОНКУ 2 НЕДЕЛИ", rarity: "Legendary", file: "kogda.png" },
  { id: "cust_nedely", name: "Я УЖЕ НЕДЕЛЮ НЕ БРИЛ СВОИ ЯЙЦА", rarity: "Legendary", file: "nedely.png" },
  { id: "cust_pokoe", name: "ПОКОЁ", rarity: "Mythic", file: "pokoe.png" },
  { id: "cust_otak", name: "ОТАК", rarity: "Mythic", file: "otak.png" },
  { id: "cust_popa", name: "ПОПОЧКА ЖОПОЧКА", rarity: "Legendary", file: "popa.png" },
  { id: "cust_skebob", name: "СКЕБОБ", rarity: "Legendary", file: "skebob.png" },
  { id: "cust_net", name: "НЕТ ИДИ НАХУЙ", rarity: "Mythic", file: "net.png" },
  { id: "cust_poshel", name: "ПОШЁЛ ТЫ НАХУЙ ПИДОР БЛЯТЬ", rarity: "Top", file: "poshel.png" },
  { id: "cust_tikorona", name: "ТЫ КОРОНА БРО???", rarity: "Top", file: "tikorona.png" },
  { id: "cust_selnapenek", name: "СЕЛ НА ПЕНЁК, КОСАРЬ ОТДАЛ.", rarity: "Top", file: "selnapenek.png" },
  { id: "cust_seriozno", name: "СЕРЬЁЗНО?ДА, СЕРЬЁЗНО", rarity: "Top", file: "seriozno.png" },
  { id: "cust_tiktotakoi", name: "ТЫ КТО ТАКОЙ?ДАВАЙ ДО СВИДАНИЯ!", rarity: "Legendary", file: "tiktotakoi.png" },
  { id: "cust_tyntyntyn", name: "ТУМАЕВ ПЕРДУН", rarity: "Legendary", file: "tyntyntyn.png" },
  { id: "cust_startyem", name: "СТАРТУЕМ!!!", rarity: "Top", file: "startyem.png" },
  { id: "cust_epstein", name: "ЭПШТЕЙН", rarity: "Legendary", file: "epstein.png" },
  { id: "cust_jamal", name: "ДЖАМАЛ", rarity: "Epic", file: "jamal.png" },
  { id: "cust_dryn", name: "ДРУН", rarity: "Mythic", file: "dryn.png" },
  { id: "cust_zinka", name: "ЖИНКА", rarity: "Legendary", file: "zinka.png" },
  { id: "cust_kolbasenko", name: "КОЛБАСЕНКО", rarity: "Legendary", file: "kolbasenko.png" },
  { id: "cust_litenergy", name: "ЛИТ ЭНЕРДЖИ", rarity: "Legendary", file: "litenergy.png" },
  { id: "cust_krytishka", name: "КРУТЫШКА", rarity: "Top", file: "krytishka.png" },
  { id: "cust_maxim", name: "МАКСИМ", rarity: "Top", file: "max.png" },
  { id: "cust_osuzhdayu", name: "ОСУЖДАААЮ", rarity: "Legendary", file: "jgbt.png" },
];

export function buildMemeSkinEntries() {
  return MEME_SKIN_DEFS.map((def) => ({
    id: def.id,
    name: def.name,
    rarity: def.rarity,
    type: "image",
    value: `${def.assetDir || "assets/images/skins"}/${def.file}`,
    caseGroup: "premium",
    sound: null,
  }));
}
